import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const source = readFileSync(new URL("./layout.tsx", import.meta.url), "utf8");

describe("root layout metadata", () => {
  it("uses exact, truthful SourcePilot metadata", () => {
    expect(source).toContain('title: "SourcePilot"');
    expect(source).toContain(
      'description: "Supplier comparison and payment approval demo."',
    );
  });

  it("removes framework scaffold metadata", () => {
    expect(source).not.toMatch(
      /Create Next App|Generated by create next app|Vercel/i,
    );
  });

  it("remains a server layout without adding UI or independent claims", () => {
    expect(source).not.toMatch(/["']use client["']/);
    expect(source).toMatch(
      /<body className="min-h-full flex flex-col">\{children\}<\/body>/,
    );
    expect(source).not.toMatch(
      /openGraph|keywords|applicationName|authors|creator|publisher/,
    );
  });
});
